### PR TITLE
Made more accessible.

### PR DESCRIPTION
**Pull request by rachancheet**
added README_english.md

### CODE REVIEW

**Comment by theowenyoung** [comment]
Hi, thanks for the pr, is seems some links are still broken, for example:

`[Click here to view use cases/screenshots] (https://immersive-translate.owenyoung.com/usecase )`

we should update it like this:

`[Click here to view use cases/screenshots](https://immersive-translate.owenyoung.com/usecase )`

**Comment by rachancheet** [comment]
Are there any other issues?

**Comment by theowenyoung** [comment]
Screenshot 2023-03-20 at 15 07 15

Hi, yes, it seems there are some conflicts here?

**Comment by theowenyoung** [comment]
Thanks!

**Comment by rachancheet** [comment]
Welcome

**Pull request merged**
